"""rename message to content

Revision ID: 045c669ad3f3
Revises: ba1703f21b9d
Create Date: 2026-07-11 14:16:49.174353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '045c669ad3f3'
down_revision: Union[str, Sequence[str], None] = 'ba1703f21b9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('content', sa.String(), nullable=True))
    op.drop_column('notifications', 'message')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('notifications', 'content')
    # ### end Alembic commands ###
