"""add board_id to users

Revision ID: 12569c98d532
Revises: 9631dcd50eb4
Create Date: 2026-07-11 13:18:39.221127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12569c98d532'
down_revision: Union[str, Sequence[str], None] = '9631dcd50eb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('board_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'boards', ['board_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'board_id')
    # ### end Alembic commands ###
