"""add board_id to users

Revision ID: 3f8c6db50025
Revises: 12569c98d532
Create Date: 2026-07-11 13:30:33.368341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f8c6db50025'
down_revision: Union[str, Sequence[str], None] = '12569c98d532'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('board_columns', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_board_columns_id'), table_name='board_columns')
    op.drop_index(op.f('ix_board_columns_name'), table_name='board_columns')
    op.alter_column('boards', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_boards_id'), table_name='boards')
    op.drop_index(op.f('ix_boards_name'), table_name='boards')
    op.drop_constraint(op.f('boards_project_id_fkey'), 'boards', type_='foreignkey')
    op.drop_column('boards', 'created_at')
    op.drop_column('boards', 'project_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('boards', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('boards_project_id_fkey'), 'boards', 'projects', ['project_id'], ['id'])
    op.create_index(op.f('ix_boards_name'), 'boards', ['name'], unique=True)
    op.create_index(op.f('ix_boards_id'), 'boards', ['id'], unique=False)
    op.alter_column('boards', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_board_columns_name'), 'board_columns', ['name'], unique=True)
    op.create_index(op.f('ix_board_columns_id'), 'board_columns', ['id'], unique=False)
    op.alter_column('board_columns', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
